
#AWS Configuration (config.yml)
#------------------------------
#This YAML file provides configuration settings for connecting to AWS services,
#specifically for use with SageMaker pipelines and related ML workflows.

#Fields:
#- account_id:         The AWS account number (string).
#- region:             The AWS region where resources are deployed (string).
#- sagemaker_role_arn: The ARN of the IAM role SageMaker uses for execution (string).
#- s3_bucket:          (Optional) Default S3 bucket for input/output data (string).

#Update these values with your AWS account details before running any AWS-related scripts.
#"

# AWS configuration file for SageMaker and related services.
# This file stores the necessary identifiers and settings for connecting to your AWS environment.

# AWS Account ID
account_id: "<your-aws-account-id>"

# AWS Region (e.g., us-east-1)
region: "<your-aws-region>"

# SageMaker execution role ARN
sagemaker_role_arn: "<your-sagemaker-execution-role-arn>"

# (Optional) S3 bucket for input/output data
s3_bucket: "<your-s3-bucket-name>"