name: Train Model in SageMaker (Development & Production)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-dev:
    name: Train Model in Development
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Submit Dev Training Job
        run: |
          aws sagemaker start-pipeline-execution --pipeline-name MLopsCronosPipelineDev --parameters \
            ParameterKey=InputDataS3,ParameterValue=s3://your-bucket/dev-data/ \
            ParameterKey=TrainingInstanceType,ParameterValue=ml.c5.2xlarge

  require-approval:
    name: Require Approval Before Production
    runs-on: ubuntu-latest
    needs: train-dev
    environment: production
    steps:
      - name: Await Reviewer Approval
        run: |
          echo "Waiting for approval before proceeding with production job..."
          # This step will pause if environment protection rules are enabled

  train-prod:
    name: Train Model in Production
    runs-on: ubuntu-latest
    needs: require-approval
    environment: production
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Submit Prod Training Job
        run: |
          aws sagemaker start-pipeline-execution --pipeline-name MLopsCronosPipelineProd --parameters \
            ParameterKey=InputDataS3,ParameterValue=s3://your-bucket/prod-data/ \
            ParameterKey=TrainingInstanceType,ParameterValue=ml.c5.4xlarge